// NPP plugin platform for .Net v0.94.00 by Kasper B. Graversen etc.
namespace ____NppPlugin____.PluginInfrastructure;

public interface IScintillaGateway
{
    void AddRefDocument(int doc);
    int AddSelection(int caret, int anchor);
    void AddStyledText(int length, Cells c);
    void AddTabStop(int line, int x);
    void AddText(string text);
    void AddText(int length, string text);
    void AddUndoAction(int token, int flags);
    void Allocate(int bytes);
    int AllocateExtendedStyles(int numberStyles);
    int AllocateSubStyles(int styleBase, int numberStyles);
    void AnnotationClearAll();
    int AnnotationGetLines(int line);
    int AnnotationGetStyle(int line);
    int AnnotationGetStyleOffset();
    string AnnotationGetStyles(int line);
    string AnnotationGetText(int line);
    int AnnotationGetVisible();
    void AnnotationSetStyle(int line, int style);
    void AnnotationSetStyleOffset(int style);
    void AnnotationSetStyles(int line, string styles);
    void AnnotationSetText(int line, string text);
    void AnnotationSetVisible(int visible);
    void AppendText(int length, string text);
    void AppendTextAndMoveCursor(string text);
    void AssignCmdKey(KeyModifier km, int msg);
    bool AutoCActive();
    void AutoCCancel();
    void AutoCComplete();
    bool AutoCGetAutoHide();
    bool AutoCGetCancelAtStart();
    int AutoCGetCaseInsensitiveBehaviour();
    bool AutoCGetChooseSingle();
    int AutoCGetCurrent();
    string AutoCGetCurrentText();
    bool AutoCGetDropRestOfWord();
    bool AutoCGetIgnoreCase();
    int AutoCGetMaxHeight();
    int AutoCGetMaxWidth();
    int AutoCGetMulti();
    int AutoCGetOrder();
    int AutoCGetSeparator();
    int AutoCGetTypeSeparator();
    Position AutoCPosStart();
    void AutoCSelect(string text);
    void AutoCSetAutoHide(bool autoHide);
    void AutoCSetCancelAtStart(bool cancel);
    void AutoCSetCaseInsensitiveBehaviour(int behaviour);
    void AutoCSetChooseSingle(bool chooseSingle);
    void AutoCSetDropRestOfWord(bool dropRestOfWord);
    void AutoCSetFillUps(string characterSet);
    void AutoCSetIgnoreCase(bool ignoreCase);
    void AutoCSetMaxHeight(int rowCount);
    void AutoCSetMaxWidth(int characterCount);
    void AutoCSetMulti(int multi);
    void AutoCSetOrder(int order);
    void AutoCSetSeparator(int separatorCharacter);
    void AutoCSetTypeSeparator(int separatorCharacter);
    void AutoCShow(int lenEntered, string itemList);
    void AutoCStops(string characterSet);
    void BackTab();
    void BeginUndoAction();
    void BraceBadLight(Position pos);
    void BraceBadLightIndicator(bool useBraceBadLightIndicator, int indicator);
    void BraceHighlight(Position pos1, Position pos2);
    void BraceHighlightIndicator(bool useBraceHighlightIndicator, int indicator);
    Position BraceMatch(Position pos);
    bool CallTipActive();
    void CallTipCancel();
    Position CallTipPosStart();
    void CallTipSetBack(Colour back);
    void CallTipSetFore(Colour fore);
    void CallTipSetForeHlt(Colour fore);
    void CallTipSetHlt(int start, int end);
    void CallTipSetPosition(bool above);
    void CallTipSetPosStart(int posStart);
    void CallTipShow(Position pos, string definition);
    void CallTipUseStyle(int tabSize);
    void Cancel();
    bool CanPaste();
    bool CanRedo();
    bool CanUndo();
    void ChangeInsertion(int length, string text);
    int ChangeLexerState(Position start, Position end);
    void CharLeft();
    void CharLeftExtend();
    void CharLeftRectExtend();
    Position CharPositionFromPoint(int x, int y);
    Position CharPositionFromPointClose(int x, int y);
    void CharRight();
    void CharRightExtend();
    void CharRightRectExtend();
    void ChooseCaretX();
    void Clear();
    void ClearAll();
    void ClearAllCmdKeys();
    void ClearCmdKey(KeyModifier km);
    void ClearDocumentStyle();
    void ClearRegisteredImages();
    void ClearRepresentation(string encodedCharacter);
    void ClearSelections();
    void ClearSelectionToCursor();
    void ClearTabStops(int line);
    void Colourise(Position start, Position end);
    int ContractedFoldNext(int lineStart);
    void ConvertEOLs(int eolMode);
    void Copy();
    void CopyAllowLine();
    void CopyRange(Position start, Position end);
    void CopyText(int length, string text);
    int CountCharacters(int startPos, int endPos);
    int CreateDocument();
    int CreateLoader(int bytes);
    void Cut();
    void DeleteBack();
    void DeleteBackNotLine();
    void DeleteRange(Position pos, int deleteLength);
    void DelLineLeft();
    void DelLineRight();
    void DelWordLeft();
    void DelWordRight();
    void DelWordRightEnd();
    string DescribeKeyWordSets();
    string DescribeProperty(string name);
    int DistanceToSecondaryStyles();
    int DocLineFromVisible(int lineDisplay);
    void DocumentEnd();
    void DocumentEndExtend();
    void DocumentStart();
    void DocumentStartExtend();
    void DropSelectionN(int selection);
    void EditToggleOvertype();
    void EmptyUndoBuffer();
    string EncodedFromUTF8(string utf8);
    void EndUndoAction();
    void EnsureVisible(int line);
    void EnsureVisibleEnforcePolicy(int line);
    void ExpandChildren(int line, int level);
    int FindColumn(int line, int column);
    void FindIndicatorFlash(Position start, Position end);
    void FindIndicatorHide();
    void FindIndicatorShow(Position start, Position end);
    Position FindText(int flags, TextToFind ft);
    void FoldAll(int action);
    void FoldChildren(int line, int action);
    void FoldLine(int line, int action);
    void FormFeed();
    void FreeSubStyles();
    Colour GetAdditionalCaretFore();
    bool GetAdditionalCaretsBlink();
    bool GetAdditionalCaretsVisible();
    int GetAdditionalSelAlpha();
    bool GetAdditionalSelectionTyping();
    bool GetAllLinesVisible();
    Position GetAnchor();
    int GetAutomaticFold();
    bool GetBackSpaceUnIndents();
    bool GetBufferedDraw();
    Colour GetCaretFore();
    Colour GetCaretLineBack();
    int GetCaretLineBackAlpha();
    bool GetCaretLineVisible();
    bool GetCaretLineVisibleAlways();
    int GetCaretPeriod();
    int GetCaretSticky();
    int GetCaretStyle();
    int GetCaretWidth();
    nint GetCharacterPointer();
    int GetCharAt(Position pos);
    int GetCodePage();
    int GetColumn(Position pos);
    int GetControlCharSymbol();
    string GetCurLine(int length);
    int GetCurrentLineNumber();
    Position GetCurrentPos();
    int GetCursor();
    nint GetDirectFunction();
    nint GetDirectPointer();
    nint GetDocPointer();
    Colour GetEdgeColour();
    int GetEdgeColumn();
    int GetEdgeMode();
    bool GetEndAtLastLine();
    Position GetEndStyled();
    int GetEOLMode();
    int GetExtraAscent();
    int GetExtraDescent();
    int GetFirstVisibleLine();
    bool GetFocus();
    bool GetFoldExpanded(int line);
    int GetFoldLevel(int line);
    int GetFoldParent(int line);
    int GetFontQuality();
    Position GetGapPosition();
    int GetHighlightGuide();
    Colour GetHotspotActiveBack();
    Colour GetHotspotActiveFore();
    bool GetHotspotActiveUnderline();
    bool GetHotspotSingleLine();
    bool GetHScrollBar();
    int GetIdentifier();
    int GetIMEInteraction();
    int GetIndent();
    int GetIndentationGuides();
    int GetIndicatorCurrent();
    int GetIndicatorValue();
    bool GetKeysUnicode();
    int GetLastChild(int line, int level);
    int GetLayoutCache();
    int GetLength();
    int GetLexer();
    string GetLexerLanguage();
    string GetLine(int line);
    int GetLineCount();
    Position GetLineEndPosition(int line);
    int GetLineEndTypesActive();
    int GetLineEndTypesAllowed();
    int GetLineEndTypesSupported();
    int GetLineIndentation(int line);
    Position GetLineIndentPosition(int line);
    Position GetLineSelEndPosition(int line);
    Position GetLineSelStartPosition(int line);
    int GetLineState(int line);
    bool GetLineVisible(int line);
    int GetMainSelection();
    int GetMarginCursorN(int margin);
    int GetMarginLeft();
    int GetMarginMaskN(int margin);
    int GetMarginOptions();
    int GetMarginRight();
    bool GetMarginSensitiveN(int margin);
    int GetMarginTypeN(int margin);
    int GetMarginWidthN(int margin);
    int GetMaxLineState();
    int GetModEventMask();
    bool GetModify();
    bool GetMouseDownCaptures();
    int GetMouseDwellTime();
    bool GetMouseSelectionRectangularSwitch();
    int GetMultiPaste();
    bool GetMultipleSelection();
    int GetNextTabStop(int line, int x);
    bool GetOvertype();
    bool GetPasteConvertEndings();
    int GetPhasesDraw();
    int GetPositionCache();
    int GetPrimaryStyleFromStyle(int style);
    int GetPrintColourMode();
    int GetPrintMagnification();
    int GetPrintWrapMode();
    string GetProperty(string key);
    string GetPropertyExpanded(string key);
    int GetPropertyInt(string key);
    string GetPunctuationChars();
    nint GetRangePointer(int position, int rangeLength);
    bool GetReadOnly();
    Position GetRectangularSelectionAnchor();
    int GetRectangularSelectionAnchorVirtualSpace();
    Position GetRectangularSelectionCaret();
    int GetRectangularSelectionCaretVirtualSpace();
    int GetRectangularSelectionModifier();
    string GetRepresentation(string encodedCharacter);
    Win32.ScrollInfo GetScrollInfo(Win32.ScrollInfoMask mask = Win32.ScrollInfoMask.SIF_ALL, Win32.ScrollInfoBar scrollBar = Win32.ScrollInfoBar.SB_BOTH);
    int GetScrollWidth();
    bool GetScrollWidthTracking();
    int GetSearchFlags();
    int GetSelAlpha();
    bool GetSelectionEmpty();
    Position GetSelectionEnd();
    int GetSelectionLength();
    int GetSelectionMode();
    Position GetSelectionNAnchor(int selection);
    int GetSelectionNAnchorVirtualSpace(int selection);
    Position GetSelectionNCaret(int selection);
    int GetSelectionNCaretVirtualSpace(int selection);
    Position GetSelectionNEnd(int selection);
    Position GetSelectionNStart(int selection);
    int GetSelections();
    Position GetSelectionStart();
    bool GetSelEOLFilled();
    string GetSelText();
    int GetStatus();
    int GetStyleAt(Position pos);
    int GetStyleBits();
    int GetStyleBitsNeeded();
    int GetStyledText(TextRange tr);
    int GetStyleFromSubStyle(int subStyle);
    string GetSubStyleBases();
    int GetSubStylesLength(int styleBase);
    int GetSubStylesStart(int styleBase);
    bool GetTabIndents();
    int GetTabWidth();
    string GetTag(int tagNumber);
    Position GetTargetEnd();
    Position GetTargetStart();
    string GetTargetText();
    int GetTechnology();
    string GetText(int length);
    int GetTextLength();
    int GetTextRange(TextRange tr);
    bool GetTwoPhaseDraw();
    bool GetUndoCollection();
    bool GetUsePalette();
    bool GetUseTabs();
    bool GetViewEOL();
    int GetViewWS();
    int GetVirtualSpaceOptions();
    bool GetVScrollBar();
    string GetWhitespaceChars();
    int GetWhitespaceSize();
    string GetWordChars();
    int GetWrapIndentMode();
    int GetWrapMode();
    int GetWrapStartIndent();
    int GetWrapVisualFlags();
    int GetWrapVisualFlagsLocation();
    int GetXOffset();
    int GetZoom();
    void GotoLine(int line);
    void GotoPos(Position pos);
    void GrabFocus();
    void HideLines(int lineStart, int lineEnd);
    void HideSelection(bool normal);
    void Home();
    void HomeDisplay();
    void HomeDisplayExtend();
    void HomeExtend();
    void HomeRectExtend();
    void HomeWrap();
    void HomeWrapExtend();
    int IndicatorAllOnFor(int position);
    void IndicatorClearRange(int position, int clearLength);
    int IndicatorEnd(int indicator, int position);
    void IndicatorFillRange(int position, int fillLength);
    int IndicatorStart(int indicator, int position);
    int IndicatorValueAt(int indicator, int position);
    int IndicGetAlpha(int indicator);
    int IndicGetFlags(int indic);
    Colour IndicGetFore(int indic);
    Colour IndicGetHoverFore(int indic);
    int IndicGetHoverStyle(int indic);
    int IndicGetOutlineAlpha(int indicator);
    int IndicGetStyle(int indic);
    bool IndicGetUnder(int indic);
    void IndicSetAlpha(int indicator, int alpha);
    void IndicSetFlags(int indic, int flags);
    void IndicSetFore(int indic, Colour fore);
    void IndicSetHoverFore(int indic, Colour fore);
    void IndicSetHoverStyle(int indic, int style);
    void IndicSetOutlineAlpha(int indicator, int alpha);
    void IndicSetStyle(int indic, int style);
    void IndicSetUnder(int indic, bool under);
    void InsertText(Position pos, string text);
    void InsertTextAndMoveCursor(string text);
    void LineCopy();
    void LineCut();
    void LineDelete();
    void LineDown();
    void LineDownExtend();
    void LineDownRectExtend();
    void LineDuplicate();
    void LineEnd();
    void LineEndDisplay();
    void LineEndDisplayExtend();
    void LineEndExtend();
    void LineEndRectExtend();
    void LineEndWrap();
    void LineEndWrapExtend();
    int LineFromPosition(Position pos);
    int LineLength(int line);
    void LineScroll(int columns, int lines);
    void LineScrollDown();
    void LineScrollUp();
    void LinesJoin();
    int LinesOnScreen();
    void LinesSplit(int pixelWidth);
    void LineTranspose();
    void LineUp();
    void LineUpExtend();
    void LineUpRectExtend();
    void LoadLexerLibrary(string path);
    void LowerCase();
    int MarginGetStyle(int line);
    int MarginGetStyleOffset();
    string MarginGetStyles(int line);
    string MarginGetText(int line);
    void MarginSetStyle(int line, int style);
    void MarginSetStyleOffset(int style);
    void MarginSetStyles(int line, string styles);
    void MarginSetText(int line, string text);
    void MarginTextClearAll();
    int MarkerAdd(int line, int markerNumber);
    void MarkerAddSet(int line, int set);
    void MarkerDefine(int markerNumber, int markerSymbol);
    void MarkerDefinePixmap(int markerNumber, string pixmap);
    void MarkerDefineRGBAImage(int markerNumber, string pixels);
    void MarkerDelete(int line, int markerNumber);
    void MarkerDeleteAll(int markerNumber);
    void MarkerDeleteHandle(int handle);
    void MarkerEnableHighlight(bool enabled);
    int MarkerGet(int line);
    int MarkerLineFromHandle(int handle);
    int MarkerNext(int lineStart, int markerMask);
    int MarkerPrevious(int lineStart, int markerMask);
    void MarkerSetAlpha(int markerNumber, int alpha);
    void MarkerSetBack(int markerNumber, Colour back);
    void MarkerSetBackSelected(int markerNumber, Colour back);
    void MarkerSetFore(int markerNumber, Colour fore);
    int MarkerSymbolDefined(int markerNumber);
    void MoveCaretInsideView();
    void MoveSelectedLinesDown();
    void MoveSelectedLinesUp();
    void NewLine();
    void Null();
    void PageDown();
    void PageDownExtend();
    void PageDownRectExtend();
    void PageUp();
    void PageUpExtend();
    void PageUpRectExtend();
    void ParaDown();
    void ParaDownExtend();
    void ParaUp();
    void ParaUpExtend();
    void Paste();
    int PointXFromPosition(Position pos);
    int PointYFromPosition(Position pos);
    Position PositionAfter(Position pos);
    Position PositionBefore(Position pos);
    Position PositionFromLine(int line);
    Position PositionFromPoint(int x, int y);
    Position PositionFromPointClose(int x, int y);
    Position PositionRelative(Position pos, int relative);
    int PrivateLexerCall(int operation, int pointer);
    string PropertyNames();
    int PropertyType(string name);
    void Redo();
    void RegisterImage(int type, string xpmData);
    void RegisterRGBAImage(int type, string pixels);
    void ReleaseAllExtendedStyles();
    void ReleaseDocument(int doc);
    void ReplaceSel(string text);
    int ReplaceTarget(int length, string text);
    int ReplaceTargetRE(int length, string text);
    void RGBAImageSetHeight(int height);
    void RGBAImageSetScale(int scalePercent);
    void RGBAImageSetWidth(int width);
    void RotateSelection();
    void ScrollCaret();
    void ScrollRange(Position secondary, Position primary);
    void ScrollToEnd();
    void ScrollToStart();
    void SearchAnchor();
    int SearchInTarget(int length, string text);
    int SearchNext(int flags, string text);
    int SearchPrev(int flags, string text);
    void SelectAll();
    void SelectCurrentLine();
    void SelectionDuplicate();
    bool SelectionIsRectangle();
    void SetAdditionalCaretFore(Colour fore);
    void SetAdditionalCaretsBlink(bool additionalCaretsBlink);
    void SetAdditionalCaretsVisible(bool additionalCaretsBlink);
    void SetAdditionalSelAlpha(int alpha);
    void SetAdditionalSelBack(Colour back);
    void SetAdditionalSelectionTyping(bool additionalSelectionTyping);
    void SetAdditionalSelFore(Colour fore);
    void SetAnchor(Position posAnchor);
    void SetAutomaticFold(int automaticFold);
    void SetBackSpaceUnIndents(bool bsUnIndents);
    void SetBufferedDraw(bool buffered);
    void SetCaretFore(Colour fore);
    void SetCaretLineBack(Colour back);
    void SetCaretLineBackAlpha(int alpha);
    void SetCaretLineVisible(bool show);
    void SetCaretLineVisibleAlways(bool alwaysVisible);
    void SetCaretPeriod(int periodMilliseconds);
    void SetCaretSticky(int useCaretStickyBehaviour);
    void SetCaretStyle(int caretStyle);
    void SetCaretWidth(int pixelWidth);
    void SetCharsDefault();
    void SetCodePage(int codePage);
    void SetControlCharSymbol(int symbol);
    void SetCurrentPos(Position pos);
    void SetCursor(int cursorType);
    void SetDocPointer(nint pointer);
    void SetEdgeColour(Colour edgeColour);
    void SetEdgeColumn(int column);
    void SetEdgeMode(int mode);
    void SetEmptySelection(Position pos);
    void SetEndAtLastLine(bool endAtLastLine);
    void SetEOLMode(int eolMode);
    void SetExtraAscent(int extraAscent);
    void SetExtraDescent(int extraDescent);
    void SetFirstVisibleLine(int lineDisplay);
    void SetFocus(bool focus);
    void SetFoldExpanded(int line, bool expanded);
    void SetFoldFlags(int flags);
    void SetFoldLevel(int line, int level);
    void SetFoldMarginColour(bool useSetting, Colour back);
    void SetFoldMarginHiColour(bool useSetting, Colour fore);
    void SetFontQuality(int fontQuality);
    void SetHighlightGuide(int column);
    void SetHotspotActiveBack(bool useSetting, Colour back);
    void SetHotspotActiveFore(bool useSetting, Colour fore);
    void SetHotspotActiveUnderline(bool underline);
    void SetHotspotSingleLine(bool singleLine);
    void SetHScrollBar(bool show);
    void SetIdentifier(int identifier);
    void SetIdentifiers(int style, string identifiers);
    void SetIMEInteraction(int imeInteraction);
    void SetIndent(int indentSize);
    void SetIndentationGuides(int indentView);
    void SetIndicatorCurrent(int indicator);
    void SetIndicatorValue(int value);
    void SetKeysUnicode(bool keysUnicode);
    void SetKeyWords(int keywordSet, string keyWords);
    void SetLayoutCache(int mode);
    void SetLengthForEncode(int bytes);
    void SetLexer(int lexer);
    void SetLexerLanguage(string language);
    void SetLineEndTypesAllowed(int lineEndBitSet);
    void SetLineIndentation(int line, int indentSize);
    void SetLineState(int line, int state);
    void SetMainSelection(int selection);
    void SetMarginCursorN(int margin, int cursor);
    void SetMarginLeft(int pixelWidth);
    void SetMarginMaskN(int margin, int mask);
    void SetMarginOptions(int marginOptions);
    void SetMarginRight(int pixelWidth);
    void SetMarginSensitiveN(int margin, bool sensitive);
    void SetMarginTypeN(int margin, int marginType);
    void SetMarginWidthN(int margin, int pixelWidth);
    void SetModEventMask(int mask);
    void SetMouseDownCaptures(bool captures);
    void SetMouseDwellTime(int periodMilliseconds);
    void SetMouseSelectionRectangularSwitch(bool mouseSelectionRectangularSwitch);
    void SetMultiPaste(int multiPaste);
    void SetMultipleSelection(bool multipleSelection);
    void SetOvertype(bool overtype);
    void SetPasteConvertEndings(bool convert);
    void SetPhasesDraw(int phases);
    void SetPositionCache(int size);
    void SetPrintColourMode(int mode);
    void SetPrintMagnification(int magnification);
    void SetPrintWrapMode(int mode);
    void SetProperty(string key, string value);
    void SetPunctuationChars(string characters);
    void SetReadOnly(bool readOnly);
    void SetRectangularSelectionAnchor(Position posAnchor);
    void SetRectangularSelectionAnchorVirtualSpace(int space);
    void SetRectangularSelectionCaret(Position pos);
    void SetRectangularSelectionCaretVirtualSpace(int space);
    void SetRectangularSelectionModifier(int modifier);
    void SetRepresentation(string encodedCharacter, string representation);
    void SetSavePoint();
    void SetScrollWidth(int pixelWidth);
    void SetScrollWidthTracking(bool tracking);
    void SetSearchFlags(int flags);
    void SetSel(Position start, Position end);
    void SetSelAlpha(int alpha);
    void SetSelBack(bool useSetting, Colour back);
    int SetSelection(int caret, int anchor);
    void SetSelectionEnd(Position pos);
    void SetSelectionMode(int mode);
    void SetSelectionNAnchor(int selection, Position posAnchor);
    void SetSelectionNAnchorVirtualSpace(int selection, int space);
    void SetSelectionNCaret(int selection, Position pos);
    void SetSelectionNCaretVirtualSpace(int selection, int space);
    void SetSelectionNEnd(int selection, Position pos);
    void SetSelectionNStart(int selection, Position pos);
    void SetSelectionStart(Position pos);
    void SetSelEOLFilled(bool filled);
    void SetSelFore(bool useSetting, Colour fore);
    void SetStatus(int statusCode);
    void SetStyleBits(int bits);
    void SetStyling(int length, int style);
    void SetStylingEx(int length, string styles);
    void SetTabIndents(bool tabIndents);
    void SetTabWidth(int tabWidth);
    void SetTargetEnd(Position pos);
    void SetTargetRange(Position start, Position end);
    void SetTargetStart(Position pos);
    void SetTechnology(int technology);
    void SetText(string text);
    void SetTwoPhaseDraw(bool twoPhase);
    void SetUndoCollection(bool collectUndo);
    void SetUsePalette(bool usePalette);
    void SetUseTabs(bool useTabs);
    void SetViewEOL(bool visible);
    void SetViewWS(int viewWS);
    void SetVirtualSpaceOptions(int virtualSpaceOptions);
    void SetVisiblePolicy(int visiblePolicy, int visibleSlop);
    void SetVScrollBar(bool show);
    void SetWhitespaceBack(bool useSetting, Colour back);
    void SetWhitespaceChars(string characters);
    void SetWhitespaceFore(bool useSetting, Colour fore);
    void SetWhitespaceSize(int size);
    void SetWordChars(string characters);
    void SetWrapIndentMode(int mode);
    void SetWrapMode(int mode);
    void SetWrapStartIndent(int indent);
    void SetWrapVisualFlags(int wrapVisualFlags);
    void SetWrapVisualFlagsLocation(int wrapVisualFlagsLocation);
    void SetXCaretPolicy(int caretPolicy, int caretSlop);
    void SetXOffset(int newOffset);
    void SetYCaretPolicy(int caretPolicy, int caretSlop);
    void SetZoom(int zoom);
    void ShowLines(int lineStart, int lineEnd);
    void StartRecord();
    void StartStyling(Position pos, int mask);
    void StopRecord();
    void StutteredPageDown();
    void StutteredPageDownExtend();
    void StutteredPageUp();
    void StutteredPageUpExtend();
    void StyleClearAll();
    Colour StyleGetBack(int style);
    bool StyleGetBold(int style);
    int StyleGetCase(int style);
    bool StyleGetChangeable(int style);
    int StyleGetCharacterSet(int style);
    bool StyleGetEOLFilled(int style);
    string StyleGetFont(int style);
    Colour StyleGetFore(int style);
    bool StyleGetHotSpot(int style);
    bool StyleGetItalic(int style);
    int StyleGetSize(int style);
    int StyleGetSizeFractional(int style);
    bool StyleGetUnderline(int style);
    bool StyleGetVisible(int style);
    int StyleGetWeight(int style);
    void StyleResetDefault();
    void StyleSetBack(int style, Colour back);
    void StyleSetBold(int style, bool bold);
    void StyleSetCase(int style, int caseForce);
    void StyleSetChangeable(int style, bool changeable);
    void StyleSetCharacterSet(int style, int characterSet);
    void StyleSetEOLFilled(int style, bool filled);
    void StyleSetFont(int style, string fontName);
    void StyleSetFore(int style, Colour fore);
    void StyleSetHotSpot(int style, bool hotspot);
    void StyleSetItalic(int style, bool italic);
    void StyleSetSize(int style, int sizePoints);
    void StyleSetSizeFractional(int style, int caseForce);
    void StyleSetUnderline(int style, bool underline);
    void StyleSetVisible(int style, bool visible);
    void StyleSetWeight(int style, int weight);
    void SwapMainAnchorCaret();
    void Tab();
    string TargetAsUTF8();
    void TargetFromSelection();
    int TextHeight(int line);
    int TextWidth(int style, string text);
    void ToggleCaretSticky();
    void ToggleFold(int line);
    void Undo();
    void UpperCase();
    void UsePopUp(bool allowPopUp);
    void UserListShow(int listType, string itemList);
    void VCHome();
    void VCHomeDisplay();
    void VCHomeDisplayExtend();
    void VCHomeExtend();
    void VCHomeRectExtend();
    void VCHomeWrap();
    void VCHomeWrapExtend();
    void VerticalCentreCaret();
    int VisibleFromDocLine(int line);
    int WordEndPosition(Position pos, bool onlyWordCharacters);
    void WordLeft();
    void WordLeftEnd();
    void WordLeftEndExtend();
    void WordLeftExtend();
    void WordPartLeft();
    void WordPartLeftExtend();
    void WordPartRight();
    void WordPartRightExtend();
    void WordRight();
    void WordRightEnd();
    void WordRightEndExtend();
    void WordRightExtend();
    int WordStartPosition(Position pos, bool onlyWordCharacters);
    int WrapCount(int line);
    void ZoomIn();
    void ZoomOut();
}